title: Hello Lynn
email: mail@hellolynn.com
description: "My design portfolio â€“ UX/UI, product, and visual design work by Lynn Nguyen."
baseurl: "" # leave empty for local dev
url: "https://www.hellolynn.com"

# Build settings
theme: null 
markdown: kramdown

# Makes URLs pretty
permalink: pretty

